services:
  vgt-api:
    image: vgt-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2138:80
    environment:
      - HOTEL_API=vgt-saga-hotel:8080
      - FLIGHT_API=vgt-saga-flight:8080
      - RABBIT_HOST=vgt-broker
      - RABBIT_PORT=5672
    networks:
      - vgt-network
networks:
  vgt-network:
    name: vgt-network
    external: true
